### ISSUE TITLE
项目很好，大佬能否把Demo程序提供下源码，最近打算重构屎山了。

### ISSUE THREAD

**Issue by LucterGee** [kanchenai/View-App#1]
大佬能否开源下这个项目，还是我从gitee没找到，看一些控件用法
[view_page](http://kanchenai.gitee.io/view_page)

另外有没有技术交流群呢，看提到的QQ群好像加不上。

**Comment by kanchenai** [comment]
view_page就是这个View-App打包放在gitee上的。qq群重新申请下，或者直接加我qq：2695704942

**Comment by kanchenai** [comment]
这个项目有个api说明，地址：http://kanchenai.gitee.io/view-api-page 可以根据api和实际代码一起看
